-- AlterTable
ALTER TABLE "law_document_chunks" ADD COLUMN     "original_content" TEXT;

-- NOTE (hand-edited): Prisma's autogenerated diff for this migration
-- included "DROP INDEX idx_chunks_embedding" because that ivfflat index
-- isn't (can't be) declared in schema.prisma — Prisma has no way to
-- express the ivfflat operator class, so it always sees this index as
-- undeclared drift on any migration that touches this table and tries to
-- drop it. Removed that line here so a fresh `prisma migrate deploy` on a
-- new environment still ends up with the index (created back in the
-- 20260831153944_init migration). Whoever runs the NEXT migration that
-- touches law_document_chunks should expect Prisma to try this again and
-- strip the DROP INDEX line the same way.
CREATE INDEX IF NOT EXISTS idx_chunks_embedding ON law_document_chunks
  USING ivfflat (embedding vector_cosine_ops);
